print("##############################")
print("#                            #")
print("#     Putri Maiza Azzura     #")
print("#       2510817220012        #")
print("#                            #")
print("##############################")